/* eslint-disable no-unused-vars */
// import { API_URL } from "./API_URL";
import "react-toastify/dist/ReactToastify.css";
import { API_URL } from "./API_URL";

const userId = localStorage.getItem("userid");

export const configMasters = {
  location: [
    {
      dpname: "Name",
      mandatory: "1",
      type: "text",
      default: "Enter location",
      edit: "1",
      bkname: "name",
      view: "1",
    },
  ],

  // location1: [
  //   {
  //     dpname: "Name",
  //     mandatory: "1",
  //     type: "text",
  //     default: "Enter location 1",
  //     edit: "1",
  //     bkname: "name",
  //     view: "1",
  //   },
  // ],

  location2: [
    {
      dpname: "Name",
      mandatory: "1",
      type: "text",
      default: "Enter location 2",
      edit: "1",
      bkname: "name",
      view: "1",
    },
  ],

  master: [{}],

  status: [
    {
      dpname: "Name",
      mandatory: "1",
      type: "text",
      default: "Enter Name ....",
      edit: "1",
      bkname: "name",
      view: "1",
    },
  ],

  users: [
    {
      dpname: "Username",
      mandatory: "1",
      type: "text",
      default: "Username",
      edit: "1",
      bkname: "username",
      view: "1",
    },

    {
      dpname: "Password",
      mandatory: "1",
      type: "text",
      default: "Password",
      edit: "1",
      bkname: "password",
      view: "0",
    },

    {
      dpname: "Email",
      mandatory: "1",
      type: "text",
      default: "Email",
      edit: "1",
      bkname: "email",
      view: "0",
    },

    {
      dpname: "Mobile No",
      mandatory: "1",
      type: "text",
      default: "Mobile No",
      edit: "1",
      bkname: "mobileno",
      view: "0",
    },

    {
      dpname: "Roles",
      mandatory: "1",
      type: "dropdown",
      default: "Select Role",
      select: "single",
      edit: "1",
      apilink: `${API_URL}/roles`,
      bkname: "role_id",
      view: "0",
    },

    // {
    //   dpname: "Status",
    //   mandatory: "1",
    //   type: "dropdown",
    //   default: "Status",
    //   select: "single",
    //   edit: "1",
    //   // apilink: `${API_URL}/status`,
    //   bkname: "status",
    //   view: "0",
    // },

    {
      dpname: "Hostel",
      mandatory: "1",
      type: "multiselect",
      select: "multiple",
      edit: "1",
      apilink: `${API_URL}/hostel`,
      bkname: "hostel_id",
      view: "0",
    },
    // {
    //       dpname: "Location",
    //       mandatory: "1",
    //       type: "dropdown",
    //       select: "multiple",
    //       options: ["Chennai", "Madurai", "Bangalaore"],
    //       // apilink: `${API_URL}/getMasters/location`,
    //       edit: "1",
    //       bkname: "location_id",
    //       view: "0"
    // }
  ],
  assettrackingtable: [
    {
      dpname: "Vehicle Number",
      mandatory: "1",
      type: "text",
      default: "Enter Name",
      edit: "1",
      bkname: "Vehicle Number",
      view: "1",
    },

    {
      dpname: "Product Type",
      mandatory: "1",
      type: "dropdown",
      select: "single",
      //  apilink: `${API_URL}/getMasters/producttype`,
      edit: "1",
      bkname: "Product Type",
      view: "1",
    },

    {
      dpname: "Category",
      mandatory: "1",
      type: "dropdown",
      select: "single",
      //  apilink: `${API_URL}/getMasters/category`,
      edit: "1",
      bkname: "category",
      view: "1",
    },
    {
      dpname: "Select Location",
      mandatory: "1",
      type: "dropdown",
      select: "single",
      //  apilink: `${API_URL}/getMasters/location`,
      edit: "1",
      bkname: "location",
      view: "1",
    },
    {
      dpname: "Select Brand",
      mandatory: "1",
      type: "dropdown",
      select: "single",
      //  apilink: `${API_URL}/getMasters/brand`,
      edit: "1",
      bkname: "category_id",
    },

    {
      dpname: "Select AMC Status",
      mandatory: "1",
      type: "dropdown",
      select: "single",
      //  apilink: `${API_URL}/getMasters/amcstatus`,
      edit: "1",
      bkname: "category_id",
    },
    {
      dpname: "Price",
      mandatory: "1",
      type: "number",
      default: "",
      edit: "1",
      bkname: "price",
    },

    {
      dpname: "Year of Purchase",
      mandatory: "1",
      type: "number",
      edit: "1",
      bkname: "year of purchase",
      view: "0",
    },

    {
      dpname: "Quantity",
      mandatory: "1",
      type: "number",
      edit: "1",
      bkname: "quantity",
      view: "0",
    },

    {
      dpname: "Select Status",
      mandatory: "1",
      type: "dropdown",
      select: "single",
      //  apilink: `${API_URL}/getMasters/status`,
      edit: "1",
      bkname: "status",
    },

    {
      dpname: "Attachment",
      mandatory: "1",
      type: "file",
      edit: "1",
      bkname: "attachment",
      view: "0",
    },

    {
      dpname: "Remarks",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "remarks",
      view: "0",
    },
  ],

  roles: [
    {
      dpname: "Name",
      mandatory: "1",
      type: "text",
      default: "Name",
      edit: "1",
      bkname: "name",
      view: "1",
    },
    {
      dpname: "Permissions",
      mandatory: "1",
      type: "multiselect-checkbox",
      select: "multiple",
      edit: "1",
      apilink: `${API_URL}/permissions`,
      options: ["Chennai", "Madurai", "Bangalaore"],
      bkname: "permissions",
      view: "0",
    },
  ],

  permissions: [
    {
      dpname: "Name",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "name",
      view: "1",
    },
  ],
  sidebar: [
    {
      dpname: "Name",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "name",
      view: "1",
    },
    {
      dpname: "Icon",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "icon",
      view: "1",
    },

    {
      dpname: "Path",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "path",
      view: "1",
    },

    {
      dpname: "Permissions",
      mandatory: "1",
      type: "dropdown",
      select: "single",
      edit: "1",
      apilink: `${API_URL}/permissions`,
      bkname: "permission",
      view: "0",
    },
  ],
  allowedtime: [
    {
      dpname: "Hostel",
      mandatory: "1",
      type: "dropdown",
      edit: "1",
      select: "single",
      apilink: `${API_URL}/hostel`,
      bkname: "hostel_id",
      view: "1",
    },

    {
      dpname: "Allowed Out Time",
      mandatory: "1",
      type: "time",
      edit: "1",
      bkname: "allowed_out_time",
      view: "1",
    },
    {
      dpname: "Expected Return Time",
      mandatory: "1",
      type: "time",
      edit: "1",
      bkname: "expected_return_time",
      view: "1",
    },

    // {
    //   dpname: "Gate Name (Optional)",
    //   mandatory: "0",
    //   type: "select",
    //   select: "single",
    //   edit: "1",
    //   apilink: `${API_URL}/gate`,
    //   bkname: "gate_id",
    //   view: "1",
    // },

    // {
    //   dpname: "Location",
    //   mandatory: "1",
    //   type: "select",
    //   select: "single",
    //   edit: "1",
    //   apilink: `${API_URL}/location`,
    //   bkname: "location",
    //   view: "1",
    // },
    // {
    //   dpname: "Status",
    //   mandatory: "1",
    //   type: "select",
    //   select: "single",
    //   edit: "1",
    //   bkname: "status",
    //   view: "1",
    // },
  ],
  department: [
    {
      dpname: "Department Name",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "department_name",
      view: "1",
    },
    {
      dpname: "Department Code",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "department_code",
      view: "1",
    },
    {
      dpname: "Status",
      mandatory: "1",
      type: "select",
      select: "single",
      edit: "1",
      bkname: "status",
      view: "1",
    },
  ],
  location1: [
    {
      dpname: "Hostel Name / Location",
      mandatory: "1",
      type: "select",
      select: "single",
      edit: "1",
      apilink: `${API_URL}/location`,
      bkname: "hostel_location",
      view: "1",
    },
    {
      dpname: "Block / Floor",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "block_floor",
      view: "1",
    },
    {
      dpname: "Room Number",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "room_no",
      view: "1",
    },
    {
      dpname: "Room Capacity",
      mandatory: "1",
      type: "number",
      edit: "1",
      bkname: "room_capacity",
      view: "1",
    },
    {
      dpname: "Room Type",
      mandatory: "1",
      type: "select",
      select: "single",
      options: ["Single", "Double", "Shared"],
      edit: "1",
      bkname: "room_type",
      view: "1",
    },
    {
      dpname: "Status",
      mandatory: "1",
      type: "select",
      select: "single",
      edit: "1",
      bkname: "status",
      view: "1",
    },
  ],
  degree: [
    {
      dpname: "Name",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "name",
      view: "1",
    },
  ],
  hostel: [
    {
      dpname: "Hostel Name",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "name",
      view: "1",
    },
    {
      dpname: "Location / Address",
      mandatory: "1",
      type: "textarea",
      edit: "1",
      bkname: "address",
      view: "1",
    },
    {
      dpname: "Warden Name",
      mandatory: "1",
      type: "text",
      edit: "1",
      bkname: "warden_name",
      view: "1",
    },
    {
      dpname: "Warden Contact",
      mandatory: "1",
      type: "number",
      edit: "1",
      bkname: "warden_contact",
      view: "1",
    },
    {
      dpname: "Hostel Type",
      mandatory: "1",
      type: "select",
      select: "single",
      options: [
        { label: "Boys", value: "Boys" },
        { label: "Girls", value: "Girls" },
        { label: "Mixed", value: "Mixed" },
      ],
      edit: "1",
      bkname: "hostel_type",
      view: "1",
    },
    {
      dpname: "Total Rooms",
      mandatory: "0",
      type: "number",
      edit: "1",
      bkname: "total_rooms",
      view: "0",
    },
    {
      dpname: "Enable Overdue SMS Alert",
      mandatory: "0",
      type: "checkbox",
      edit: "1",
      bkname: "sms_alert",
      view: "1",
      default: false,
    },
    {
      dpname: "Alert Order",
      mandatory: "0",
      type: "select",
      select: "single",
      options: [
        { label: "Warden First, then Parent", value: "warden_parent" },
        { label: "Direct Parent", value: "parent_direct" },
      ],
      edit: "1",
      bkname: "alert_order",
      view: "1",
      dependency: "sms_alert",
    },
    // {
    //   dpname: "Status",
    //   mandatory: "1",
    //   type: "select",
    //   select: "single",
    //   options: [
    //     { label: "Active", value: "Active" },
    //     { label: "Inactive", value: "Inactive" },
    //   ],
    //   edit: "1",
    //   bkname: "status",
    //   view: "1",
    // },
  ],
  gender: [
    {
      dpname: "Name",
      mandatory: "1",
      type: "text",
      default: "Enter Name ....",
      edit: "1",
      bkname: "name",
      view: "1",
    },
  ],
  smsconfiguration: [
    {
      dpname: "Hostel",
      bkname: "hostel_id",
      type: "dropdown",
      mandatory: "1",
      options: [], // filled dynamically with hostels
    },
    {
      dpname: "SMS Alert Type",
      bkname: "sms_alert_type",
      type: "select",
      mandatory: "1",
      options: [
        { label: "Manual", value: "manual" },
        { label: "Automatic", value: "automatic" },
      ],
    },
  ],
};
