import { API_URL } from "./API_URL";

export const configReports = {
  inOutMovement: {
    header: [
      "S.No",
      "Member ID",
      "Name",
      "Out Time",
      "In Time",
      "Hostel",
      "Over Due",
    ],
    fields: [
      {
        dpname: "From Date",
        mandatory: "1",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "fromDate",
        view: false,
        showInExpanded: false,
        backendAccessKey: "out_time",
        showInFilter: true,
      },
      {
        dpname: "To Date",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "toDate",
        view: false,
        showInExpanded: false,
        showInFilter: true,
      },
      {
        dpname: "Member ID",
        type: "text",
        default: "Enter Member ID",
        bkname: "memberid",
        view: true,
        showInExpanded: false,
        backendAccessKey: "memberid",
        showInFilter: true,
      },
      {
        dpname: "Name",
        bkname: "name",
        view: true,
        backendAccessKey: "name",
        showInFilter: false,
      },
      {
        dpname: "Out Time",
        bkname: "out_time",
        view: true,
        backendAccessKey: "out_time",
        showInFilter: false,
      },
      {
        dpname: "In Time",
        bkname: "in_time",
        view: true,
        backendAccessKey: "in_time",
        showInFilter: false,
      },
      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: true,
        showInFilter: true, // show only in filter area
        backendAccessKey: "hostel",
        apilink: `${API_URL}/hostel`,
      },
      {
        dpname: "overdue",
        bkname: "overdue",
        view: true,
        backendAccessKey: "overdue",
        showInFilter: false,
      },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },

  lateReturn: {
    header: [
      "S.No",
      "Member ID",
      "Name",
      "Out Time",
      "In Time",
      // "Reason",
      "Hostel",
    ],
    fields: [
      {
        dpname: "From Date",
        mandatory: "1",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "fromDate",
        view: false,
        showInExpanded: false,
        backendAccessKey: "out_time",
        showInFilter: true,
      },
      {
        dpname: "To Date",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "toDate",
        view: false,
        showInExpanded: false,
        showInFilter: true,
      },
      // {
      //   dpname: "Min Delay (min)",
      //   type: "number",
      //   default: "Enter Minimum Delay",
      //   bkname: "minDelay",
      //   view: true,
      //   showInExpanded: false,
      //   backendAccessKey: "delay",
      //   showInFilter: true,
      // },
      {
        dpname: "Member ID",
        type: "text",
        default: "Enter Member ID",
        bkname: "memberid",
        view: true,
        showInExpanded: false,
        backendAccessKey: "memberid",
        showInFilter: true,
      },
      {
        dpname: "Name",
        bkname: "name",
        view: true,
        backendAccessKey: "name",
        showInFilter: false,
      },
      {
        dpname: "Out Time",
        bkname: "out_time",
        view: true,
        backendAccessKey: "out_time",
        showInFilter: false,
      },
      {
        dpname: "In Time",
        bkname: "in_time",
        view: true,
        backendAccessKey: "in_time",
        showInFilter: false,
      },
      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: true,
        showInFilter: true, // show only in filter area
        backendAccessKey: "hostel",
        apilink: `${API_URL}/hostel`,
      },
      // {
      //   dpname: "Reason",
      //   bkname: "status",
      //   view: true,
      //   backendAccessKey: "status",
      //   showInFilter: false,
      // },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },

  studentsOutside: {
    header: [
      "S.No",
      "Member ID",
      "Name",
      "Out Time",
      "Overdue Status",
      "Minutes Overdue",
    ],
    fields: [
      {
        dpname: "Member ID",
        type: "text",
        default: "Enter Member ID",
        bkname: "memberid",
        view: true,
        showInExpanded: false,
        backendAccessKey: "memberid",
        showInFilter: false,
      },
      {
        dpname: "Name",
        bkname: "name",
        view: true,
        backendAccessKey: "name",
        showInFilter: false,
      },
      {
        dpname: "Out Time",
        bkname: "out_time",
        view: true,
        backendAccessKey: "out_time",
        showInFilter: false,
      },

      {
        dpname: "Overdue Status",
        bkname: "overdue_status",
        view: true,
        backendAccessKey: "overdue_status",
        showInFilter: false,
      },
      {
        dpname: "Minutes Overdue",
        bkname: "overdue_minutes",
        view: true,
        backendAccessKey: "overdue_minutes",
        showInFilter: false,
      },
      // dropdown filter
      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: false,
        showInFilter: true, // show only in filter area
        backendAccessKey: "hostel",
        apilink: `${API_URL}/hostel`,
      },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },

  studentsInside: {
    header: ["S.No", "Member ID", "Name", "Out Time", "In Time"],
    fields: [
      {
        dpname: "Member ID",
        type: "text",
        default: "Enter Member ID",
        bkname: "memberid",
        view: true,
        showInExpanded: false,
        backendAccessKey: "memberid",
        showInFilter: false,
      },
      {
        dpname: "Name",
        bkname: "name",
        view: true,
        backendAccessKey: "name",
        showInFilter: false,
      },
      {
        dpname: "Out Time",
        bkname: "out_time",
        view: true,
        backendAccessKey: "out_time",
        showInFilter: false,
      },

      {
        dpname: "In Time",
        bkname: "in_time",
        view: true,
        backendAccessKey: "in_time",
        showInFilter: false,
      },
      // dropdown filter
      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: false,
        showInFilter: true, // show only in filter area
        backendAccessKey: "hostel",
        apilink: `${API_URL}/hostel`,
      },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },

  summaryReport: {
    header: ["S.No", "Member ID", "Name", "Mobile", "Email", "Expiry Date"],
    fields: [
      {
        dpname: "From Date",
        mandatory: "1",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "fromDate",
        view: false,
        showInExpanded: false,
        showInFilter: true,
      },
      {
        dpname: "To Date",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "toDate",
        view: false,
        showInExpanded: false,
        showInFilter: true,
      },
      {
        dpname: "Member ID",
        type: "text",
        default: "Enter Member ID",
        bkname: "memberid",
        view: true,
        showInExpanded: false,
        backendAccessKey: "memberid",
        showInFilter: true,
      },
      {
        dpname: "Name",
        bkname: "name",
        type: "text",
        view: true,
        showInFilter: true,
      },
      {
        dpname: "Mobile",
        bkname: "mobile",
        type: "text",
        view: true,
        showInFilter: true,
      },
      {
        dpname: "Email",
        bkname: "email",
        type: "text",
        view: true,
        showInFilter: false,
      },

      {
        dpname: "Expiry Date",
        bkname: "expirydate",
        type: "date",
        view: true,
        showInFilter: true,
        minDate: new Date().toISOString().split("T")[0], // restrict past dates
      },

      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: false,
        apilink: `${API_URL}/hostel`,
        backendAccessKey: "name",
        mergeKeys: ["location", "location1", "location2"],
        showInFilter: true,
      },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },

  smslog: {
    header: [
      "S.No",
      "Student Name",
      "Hostel",
      "SMS Sent At",
      // "Reminder Sent At",
      "Status",
      "Created By",
    ],
    fields: [
      {
        dpname: "From Date",
        mandatory: "1",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "fromDate",
        view: false,
        showInExpanded: false,
        showInFilter: true,
      },
      {
        dpname: "To Date",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "toDate",
        view: false,
        showInExpanded: false,
        showInFilter: true,
      },
      // {
      //   dpname: "Member ID",
      //   type: "text",
      //   default: "Enter Member ID",
      //   bkname: "memberid",
      //   view: false,
      //   backendAccessKey: "student_id",
      //   showInFilter: true,
      // },

      {
        dpname: "student_name",
        type: "text",
        bkname: "student_name",
        view: true,
        backendAccessKey: "student_name",
        showInFilter: false,
      },

      {
        dpname: "Hostel",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "hostel",
        view: false,
        showInFilter: true,
        backendAccessKey: "hostel_id",
        apilink: `${API_URL}/hostel`,
      },
      {
        dpname: "Hostel",
        bkname: "hostehostel_namel",
        view: true,
        showInFilter: false,
        backendAccessKey: "hostel_name",
      },
      {
        dpname: "SMS Sent At",
        bkname: "sms_sent_at",
        type: "datetime",
        view: true,
        showInFilter: false,
      },
      // {
      //   dpname: "Reminder Sent At",
      //   bkname: "reminder_sent_at",
      //   type: "datetime",
      //   view: true,
      //   showInFilter: false,
      // },
      {
        dpname: "sms_status",
        bkname: "sms_status",
        type: "text",
        view: true,
        showInFilter: false,
      },
      {
        dpname: "Created By",
        type: "dropdown",
        select: "single",
        bkname: "created_by",
        view: true,
        showInFilter: true,
        backendAccessKey: "created_by",
        apilink: `${API_URL}/users`,
      },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },
};
