import { API_URL } from "./API_URL";

export const configReports = {
  lastvehicletracking: {
    header: [
      "S.No",
      // "Last Tracking Date and Time",
      "Vehicle Number",
      "Vehicle Rfid",
      "Location",
      "Gate",
      // "Vehicle IN/OUT Time",
      "Status",

      // "Vehicle Type",
      // "View",
    ],
    fields: [
      // {
      //   dpname: "Vehicle IN/OUT Time",
      //   type: "datetime-local", // ✅ HTML5 date-time picker type
      //   dropdownType: "single",
      //   default: "",
      //   bkname: "transtime",
      //   view: true,
      //   showInExpanded: false,
      //   backendAccessKey: "transtime",
      // },
      {
        dpname: "FromDate",
        mandatory: "1",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "fromDate",
        view: false,
        showInExpanded: false,
        backendAccessKey: "createdat",
      },
      {
        dpname: "ToDate",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "toDate",
        view: false,
        showInExpanded: false,
      },
      {
        dpname: "vehiclenumber",
        type: "text",
        default: "Select Center",
        bkname: "vehiclenumber",
        view: true,
        showInExpanded: false,
        backendAccessKey: "vehiclenumber",
      },
      {
        dpname: "vehiclerfid",
        type: "text",
        default: "Select Center",
        bkname: "vehiclerfid",
        view: true,
        showInExpanded: true,
        backendAccessKey: "vehiclerfid",
      },
      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: true,
        showInExpanded: false,
        apilink: `${API_URL}/location`,
        backendAccessKey: "location",
        mergeKeys: ["location", "location1", "location2"],
      },
      {
        dpname: "Gate",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location1",
        view: true,
        showInExpanded: false,
        apilink: `${API_URL}/location1`,
        backendAccessKey: "location1",
      },
      // {
      //   dpname: "Room No",
      //   type: "dropdown",
      //   select: "single",
      //   default: "Select Center",
      //   bkname: "location2",
      //   view: false,
      //   showInExpanded: false,
      //   apilink: `${API_URL}/location2`,
      //   backendAccessKey: "location2",
      // },
      // {
      //   dpname: "Users",
      //   type: "dropdown",
      //   select: "single",
      //   default: "Select Center",
      //   bkname: "user",
      //   view: true,
      //   showInExpanded: true,
      //   apilink: `${API_URL}/users`,
      //   backendAccessKey: "username",
      // },
      // {
      //     dpname: "Brand",
      //     type: "dropdown",
      //     select: "single",
      //     default: "Select Center",
      //     bkname: "brand",
      //     view: false,
      //     showInExpanded: true,
      //     apilink: `${API_URL}/brand`,
      //     backendAccessKey: "name",
      // },
      // {
      //     dpname: "Status masters",
      //     mandatory: "1",
      //     type: "dropdown",
      //     select: "single",
      //     default: "Select Center",
      //     edit: "1",
      //     bkname: "status",
      //     view: "1",
      //     apilink: `${API_URL}/status`,
      //     backendAccessKey: "name",
      // },
      // {
      //     dpname: "Tag types",
      //     type: "dropdown",
      //     select: "single",
      //     default: "Select Center",
      //     bkname: "tagtype",
      //     view: false,
      //     showInExpanded: true,
      //     apilink: `${API_URL}/tagtype`,
      //     backendAccessKey: "tag_type",
      // },
      // {
      //     dpname: "Vendors",
      //     type: "dropdown",
      //     select: "single",
      //     default: "Select Center",
      //     bkname: "vendors",
      //     view: false,
      //     showInExpanded: true,
      //     apilink: `${API_URL}/vendors`,
      //     backendAccessKey: "vendor",
      // },
      // {
      //   dpname: "Vehicle IN/OUT Time",
      //   type: "text",
      //   bkname: "transtime",
      //   backendAccessKey: "transtime",
      //   view: true, // show in table
      //   showInExpanded: false, // hide from dropdown
      // },
      {
        dpname: "Status",
        type: "dropdown",
        dropdownType: "single",
        default: "Status",
        bkname: "status", // Backend key name
        view: true,
        showInExpanded: false,
        backendAccessKey: "status",
      },
      // {
      //   dpname: "Product Type",
      //   type: "dropdown",
      //   select: "single",
      //   default: "Select Product Type",
      //   bkname: "product_types",
      //   view: true,
      //   showInExpanded: false,
      //   isCategoryRoot: true,
      // },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },

  vehicledetails: {
    header: [
      "S.No",
      // "Purchased Date",
      "Vehicle Number",
      "Vehicle Rfid",
      "Location",
      // "Gate",
      "Users",
      "Status",
      "Vehicle Type",
      // "View",
    ],
    fields: [
      {
        dpname: "FromDate",
        mandatory: "1",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "fromDate",
        view: false,
        showInExpanded: false,
        backendAccessKey: "year_of_purchase",
      },
      {
        dpname: "ToDate",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "toDate",
        view: false,
        showInExpanded: false,
      },
      {
        dpname: "vehiclenumber",
        type: "text",
        default: "Select Center",
        bkname: "vehiclenumber",
        view: true,
        showInExpanded: false,
        backendAccessKey: "vehiclenumber",
      },
      {
        dpname: "vehiclerfid",
        type: "text",
        default: "Select Center",
        bkname: "vehiclerfid",
        view: true,
        showInExpanded: false,
        backendAccessKey: "vehiclerfid",
      },
      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: true,
        showInExpanded: false,
        apilink: `${API_URL}/location`,
        backendAccessKey: "location",
        mergeKeys: ["location", "location1", "location2"],
      },
      // {
      //   dpname: "Gate",
      //   type: "dropdown",
      //   select: "single",
      //   default: "Select Center",
      //   bkname: "location1",
      //   view: true,
      //   showInExpanded: false,
      //   apilink: `${API_URL}/location1`,
      //   backendAccessKey: "location1",
      // },
      // {
      //   dpname: "Room No",
      //   type: "dropdown",
      //   select: "single",
      //   default: "Select Center",
      //   bkname: "location2",
      //   view: false,
      //   showInExpanded: false,
      //   apilink: `${API_URL}/location2`,
      //   backendAccessKey: "location2",
      // },
      {
        dpname: "Users",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "user",
        view: true,
        showInExpanded: false,
        apilink: `${API_URL}/users`,
        backendAccessKey: "username",
      },
      // {
      //   dpname: "Brand",
      //   type: "dropdown",
      //   select: "single",
      //   default: "Select Center",
      //   bkname: "brand",
      //   view: false,
      //   showInExpanded: true,
      //   apilink: `${API_URL}/brand`,
      //   backendAccessKey: "brand",
      // },
      // {
      //     dpname: "Status masters",
      //     mandatory: "1",
      //     type: "dropdown",
      //     select: "single",
      //     default: "Select Center",
      //     edit: "1",
      //     bkname: "status",
      //     view: "1",
      //     apilink: `${API_URL}/status`,
      //     backendAccessKey: "name",
      // },
      // {
      //   dpname: "Tag types",
      //   type: "dropdown",
      //   select: "single",
      //   default: "Select Center",
      //   bkname: "tagtype",
      //   view: false,
      //   showInExpanded: true,
      //   apilink: `${API_URL}/tagtype`,
      //   backendAccessKey: "tag_type",
      // },
      // {
      //   dpname: "Vendors",
      //   type: "dropdown",
      //   select: "single",
      //   default: "Select Center",
      //   bkname: "vendors",
      //   view: false,
      //   showInExpanded: true,
      //   apilink: `${API_URL}/vendors`,
      //   backendAccessKey: "vendor",
      // },
      {
        dpname: "Status",
        type: "dropdown",
        dropdownType: "single",
        default: "Status",
        bkname: "status", // Backend key name
        view: true,
        showInExpanded: false,
        backendAccessKey: "status",
      },

      {
        dpname: "Vehicle Type",
        type: "dropdown",
        select: "single",
        default: "Select Product Type",
        bkname: "product_types",
        view: true,
        showInExpanded: false,
        isCategoryRoot: true,
      },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },
  visitorreport: {
    header: [
      "S.No",
      "Visitor Name",
      "Vehicle Number",
      "Mobile",
      "RFID Tag",
      "Location",
      "Check-In Time",
      // "Expected Exit Time",
      "Check-Out Time",
    ],

    fields: [
      {
        dpname: "From Date",
        mandatory: "1",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "fromDate",
        view: false,
        showInExpanded: false,
        backendAccessKey: "check_in",
      },
      {
        dpname: "To Date",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "toDate",
        view: false,
        showInExpanded: false,
      },
      {
        dpname: "Visitor Name",
        type: "text",
        default: "Enter Visitor Name",
        bkname: "visitor_name",
        view: true,
        backendAccessKey: "visitor_name",
      },
      {
        dpname: "Vehicle Number",
        type: "text",
        default: "Enter Vehicle Number",
        bkname: "vehicle_number",
        view: true,
        backendAccessKey: "vehicle_number",
      },
      {
        dpname: "Mobile",
        type: "text",
        default: "Enter Mobile Number",
        bkname: "mobile",
        view: true,
        backendAccessKey: "mobile",
      },
      {
        dpname: "Vehicle RFID Tag",
        type: "text",
        default: "Enter RFID Tag",
        bkname: "rfid_tag",
        view: true,
        backendAccessKey: "rfid_tag",
      },
      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Location",
        bkname: "location_id",
        view: true,
        apilink: `${API_URL}/location`,
        backendAccessKey: "location_name",
      },
      {
        dpname: "Check-In Out",
        type: "date", // ✅ date-time picker
        default: "Enter Check-In Time",
        bkname: "check_in",
        view: true,
        backendAccessKey: "check_in",
      },
      // {
      //   dpname: "Expected Exit Date",
      //   type: "date", // ✅ date-time picker
      //   default: "Enter Expected Exit Time",
      //   bkname: "expected_exit_time",
      //   view: true,
      //   backendAccessKey: "expected_exit_time",
      // },
      {
        dpname: "Check-Out Date",
        type: "date", // ✅ date-time picker
        default: "Enter Check-Out Time",
        bkname: "check_out",
        view: true,
        backendAccessKey: "check_out",
      },
    ],

    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },
  dailyInOutMovement: {
    header: ["S.No", "Member ID", "Name", "Out Time", "In Time", "Hostel"],
    fields: [
      {
        dpname: "From Date",
        mandatory: "1",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "fromDate",
        view: false,
        showInExpanded: false,
        backendAccessKey: "out_time",
        showInFilter: true,
      },
      {
        dpname: "To Date",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "toDate",
        view: false,
        showInExpanded: false,
        showInFilter: true,
      },
      {
        dpname: "Member ID",
        type: "text",
        default: "Enter Member ID",
        bkname: "memberid",
        view: true,
        showInExpanded: false,
        backendAccessKey: "memberid",
        showInFilter: true,
      },
      {
        dpname: "Name",
        bkname: "name",
        view: true,
        backendAccessKey: "name",
        showInFilter: false,
      },
      {
        dpname: "Out Time",
        bkname: "out_time",
        view: true,
        backendAccessKey: "out_time",
        showInFilter: false,
      },
      {
        dpname: "In Time",
        bkname: "in_time",
        view: true,
        backendAccessKey: "in_time",
        showInFilter: false,
      },
      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: true,
        showInFilter: true, // show only in filter area
        backendAccessKey: "hostel",
        apilink: `${API_URL}/hostel`,
      },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },

  lateReturn: {
    header: [
      "S.No",
      "Member ID",
      "Name",
      "Out Time",
      "In Time",
      // "Reason",
      "Hostel",
    ],
    fields: [
      {
        dpname: "From Date",
        mandatory: "1",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "fromDate",
        view: false,
        showInExpanded: false,
        backendAccessKey: "out_time",
        showInFilter: true,
      },
      {
        dpname: "To Date",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "toDate",
        view: false,
        showInExpanded: false,
        showInFilter: true,
      },
      // {
      //   dpname: "Min Delay (min)",
      //   type: "number",
      //   default: "Enter Minimum Delay",
      //   bkname: "minDelay",
      //   view: true,
      //   showInExpanded: false,
      //   backendAccessKey: "delay",
      //   showInFilter: true,
      // },
      {
        dpname: "Member ID",
        type: "text",
        default: "Enter Member ID",
        bkname: "memberid",
        view: true,
        showInExpanded: false,
        backendAccessKey: "memberid",
        showInFilter: true,
      },
      {
        dpname: "Name",
        bkname: "name",
        view: true,
        backendAccessKey: "name",
        showInFilter: false,
      },
      {
        dpname: "Out Time",
        bkname: "out_time",
        view: true,
        backendAccessKey: "out_time",
        showInFilter: false,
      },
      {
        dpname: "In Time",
        bkname: "in_time",
        view: true,
        backendAccessKey: "in_time",
        showInFilter: false,
      },
      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: true,
        showInFilter: true, // show only in filter area
        backendAccessKey: "hostel",
        apilink: `${API_URL}/hostel`,
      },
      // {
      //   dpname: "Reason",
      //   bkname: "status",
      //   view: true,
      //   backendAccessKey: "status",
      //   showInFilter: false,
      // },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },

  studentsOutside: {
    header: [
      "S.No",
      "Member ID",
      "Name",
      "Out Time",
      "Overdue Status",
      "Minutes Overdue",
    ],
    fields: [
      {
        dpname: "Member ID",
        type: "text",
        default: "Enter Member ID",
        bkname: "memberid",
        view: true,
        showInExpanded: false,
        backendAccessKey: "memberid",
        showInFilter: false,
      },
      {
        dpname: "Name",
        bkname: "name",
        view: true,
        backendAccessKey: "name",
        showInFilter: false,
      },
      {
        dpname: "Out Time",
        bkname: "out_time",
        view: true,
        backendAccessKey: "out_time",
        showInFilter: false,
      },

      {
        dpname: "Overdue Status",
        bkname: "overdue_status",
        view: true,
        backendAccessKey: "overdue_status",
        showInFilter: false,
      },
      {
        dpname: "Minutes Overdue",
        bkname: "overdue_minutes",
        view: true,
        backendAccessKey: "overdue_minutes",
        showInFilter: false,
      },
      // dropdown filter
      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: false,
        showInFilter: true, // show only in filter area
        backendAccessKey: "hostel",
        apilink: `${API_URL}/hostel`,
      },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },

  studentsInside: {
    header: ["S.No", "Member ID", "Name", "Out Time", "In Time"],
    fields: [
      {
        dpname: "Member ID",
        type: "text",
        default: "Enter Member ID",
        bkname: "memberid",
        view: true,
        showInExpanded: false,
        backendAccessKey: "memberid",
        showInFilter: false,
      },
      {
        dpname: "Name",
        bkname: "name",
        view: true,
        backendAccessKey: "name",
        showInFilter: false,
      },
      {
        dpname: "Out Time",
        bkname: "out_time",
        view: true,
        backendAccessKey: "out_time",
        showInFilter: false,
      },

      {
        dpname: "In Time",
        bkname: "in_time",
        view: true,
        backendAccessKey: "in_time",
        showInFilter: false,
      },
      // dropdown filter
      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: false,
        showInFilter: true, // show only in filter area
        backendAccessKey: "hostel",
        apilink: `${API_URL}/hostel`,
      },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },

  summaryReport: {
    header: [
      "S.No",
      "Member ID",
      "Name",
      "Mobile",
      "Email",
      // "Parent Name",
      // "Parent Contact",
      "Expiry Date",
      "Total IN/OUT",
      // "Total Late Returns",
      "Total Overdue",
    ],
    fields: [
      {
        dpname: "From Date",
        mandatory: "1",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "fromDate",
        view: false,
        showInExpanded: false,
        showInFilter: true,
      },
      {
        dpname: "To Date",
        type: "date",
        default: "Set Timeline",
        dropdownType: "single",
        bkname: "toDate",
        view: false,
        showInExpanded: false,
        showInFilter: true,
      },
      {
        dpname: "Member ID",
        type: "text",
        default: "Enter Member ID",
        bkname: "memberid",
        view: true,
        showInExpanded: false,
        backendAccessKey: "memberid",
        showInFilter: true,
      },
      {
        dpname: "Name",
        bkname: "name",
        type: "text",
        view: true,
        showInFilter: true,
      },
      {
        dpname: "Mobile",
        bkname: "mobile",
        type: "text",
        view: true,
        showInFilter: true,
      },
      {
        dpname: "Email",
        bkname: "email",
        type: "text",
        view: true,
        showInFilter: false,
      },
      // {
      //   dpname: "Parent Name",
      //   bkname: "parentname",
      //   type: "text",
      //   view: false,
      //   showInExpanded: false,
      // },
      // {
      //   dpname: "Parent Contact",
      //   bkname: "parentcontact",
      //   type: "text",
      //   view: true,
      // },
      {
        dpname: "Expiry Date",
        bkname: "expirydate",
        type: "date",
        view: true,
        showInFilter: true,
        minDate: new Date().toISOString().split("T")[0], // restrict past dates
      },
      {
        dpname: "Total IN/OUT",
        bkname: "total_movements",
        type: "number",
        view: true,
        showInFilter: false,
      },
      // {
      //   dpname: "Total Late Returns",
      //   bkname: "total_late",
      //   type: "number",
      //   view: true,
      //   showInFilter: false,
      // },
      {
        dpname: "Total Overdue",
        bkname: "total_outside",
        type: "number",
        view: true,
        showInFilter: false,
      },
      // Filters

      {
        dpname: "Location",
        type: "dropdown",
        select: "single",
        default: "Select Center",
        bkname: "location",
        view: false,
        apilink: `${API_URL}/hostel`,
        backendAccessKey: "name",
        mergeKeys: ["location", "location1", "location2"],
        showInFilter: true,
      },
    ],
    exportTypes: [
      { key: "excel", label: "Excel", ext: "xlsx" },
      { key: "pdf", label: "PDF", ext: "pdf" },
    ],
  },
};
